# Generated by Django 4.2.2 on 2023-10-15 05:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0003_alter_participant_position'),
    ]

    operations = [
        migrations.AlterField(
            model_name='participant',
            name='position',
            field=models.IntegerField(default=0),
        ),
    ]
