# Generated by Django 4.2.2 on 2023-08-07 21:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='block',
            fields=[
                ('index', models.IntegerField(primary_key=True, serialize=False)),
                ('proof', models.IntegerField()),
                ('prevHash', models.CharField(max_length=50)),
                ('data', models.CharField(max_length=500)),
                ('timestamp', models.DateTimeField()),
                ('users_hash', models.CharField(max_length=50)),
                ('current_hash', models.CharField(max_length=50)),
            ],
        ),
    ]
